## Importing Numpy as np

In [ ]:
import numpy as np

## Creating an Array of 10 zeros

In [7]:
import numpy as np
Morgan = np.zeros(10)
Morgan

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
## Creating an array of 10 ones

In [9]:
Morgan = np.ones(10)
Morgan

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
## Creating an array of 10 fives

In [12]:
Morgan = np.ones(10)*5
Morgan

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
## Creating an array of the integers 10 to 50

In [15]:
Morgan = np.arange(10,51)
Morgan

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
## Creating an array of all the even integers 10 to 50

In [18]:
Morgan = np.arange(10,51,2)
Morgan

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [19]:
## Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
Morgan = np.arange(0,9).reshape((3,3))
Morgan

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
## Create a 3x3 identity matrix

In [25]:
Morgan = np.eye(3,3)
Morgan

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
## Use Numpy to generate a random number between 0 and 1

In [29]:
random = np.random.randint(0,1,1)
random

array([0])

In [30]:
## Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [33]:
random_25 = np.random.normal(0,1,25)
random_25

array([-1.94199011, -1.45147226,  0.40801464, -0.72301828,  0.56220696,
       -0.87187941,  0.45248515, -0.35046083, -0.55588062,  0.33008811,
        0.42212586,  0.01126087, -1.4100458 ,  0.90474056,  1.07389916,
       -1.72806035, -0.65011156,  0.89003573,  0.9580059 , -1.29348355,
        1.00093503,  0.22965732,  0.12106848,  0.58731187, -1.92582815])

In [34]:
## Create the following matrix:

In [37]:
Morgan = np.arange(0.01,1.01,0.01).reshape(10,10)
Morgan

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
## Create an array of 20 linearly spaced points between 0 and 1

In [39]:
Victoria = np.linspace(0,1,20)
Victoria

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy indexng and Selection

In [24]:
# Write code that reproduces the output of the cell

In [46]:
mat = np.arange(1,26).reshape(5,5)
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
matt = mat[:10,4]
matt

array([ 5, 10, 15, 20, 25])

In [50]:
mat = np.arange(1,26).reshape(5,5)
mat
matt1 = mat[2:5, 1:5]
matt1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [6]:
import numpy as np
0po997//= np.arange(1,26).reshape(5,5)
matt1 = mat[3, 4]
matt1

20

In [8]:
Morgan = mat[0:3,1:2]
Morgan

array([[ 2],
       [ 7],
       [12]])

In [11]:
M = mat[4]
M

array([21, 22, 23, 24, 25])

In [12]:
M = mat[3:]
M

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
## Get the sum of all the values in mat

In [15]:
m = mat.sum()
m

325

In [16]:
## Get the standard deviation of the values in mat

In [17]:
m = mat.std()
m

7.211102550927978

In [18]:
## Get the sum of all the columns in mat

In [20]:
m = mat.sum(axis=1)
m

array([ 15,  40,  65,  90, 115])

In [21]:
## Get the sum of all the rows in mat

In [23]:
m = mat.sum(axis=0)
m

array([55, 60, 65, 70, 75])